language: c

os:
  - linux

compiler:
  - gcc

before_install:
  - sudo apt-get -qq update

install:
  - sudo apt-get install -qq libdfp1
  - sudo apt-get install -qq libdfp-dev

before_script:
  - autoreconf -vfi

script:
  - ./configure || { cat config.log; false; }
  - make clean
  - make all
  - make check || { cat test/test-suite.log; false; }
  - make distcheck

## whitelist
branches:
  only:
    - master
    - next

notifications:
  email:
    - devel@fresse.org
