language: c

os:
  - linux

compiler:
  - gcc

before_script:
  - autoreconf -vfi

script:
  - ./configure || { cat config.log; false; }
  - make clean
  - make all
  - make check || { cat test/test-suite.log; false; }
  - make distcheck

## whitelist
branches:
  only:
    - master
    - next

notifications:
  email:
    - devel@fresse.org

addons:
  apt:
    packages:
      - gsl-bin
      - libgsl0-dev
